# Generated by Django 5.0.3 on 2024-03-26 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='address',
            new_name='name',
        ),
    ]
