# Generated by Django 5.0.3 on 2024-03-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipapp', '0002_rename_address_home_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('your_name', models.CharField(blank=True, max_length=255, null=True)),
                ('your_mail', models.CharField(blank=True, max_length=255, null=True)),
                ('your_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
