# Generated by Django 5.0.3 on 2024-03-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipapp', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='select_gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
